From nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /usr/share/nginx/html/
COPY dist /usr/share/nginx/html/

#Expose ports
EXPOSE 80

#Start nginx
#CMD service nginx start
